server:
  port: 8087
spring:
  application:
    name: WalkMoreFatMan
  datasource:
#     docker run --name bju-db -p 5432:5432 -e POSTGRES_DB=diet_service
#      -e POSTGRES_USER=bjuuser -e POSTGRES_PASSWORD=bjupassword postgres:16 # создание и запуск контейнера с бд

#    url: jdbc:postgresql://host.docker.internal:5432/diet_service  # для создания контейнера
    url: jdbc:postgresql://localhost:5432/diet_service  # для запуска из среды разработки
    username: bjuuser
    password: bjupassword
  jpa:
    show-sql: true
